# 4. External Systems Profile CFN Template: VPC Endpoint for PrivateLink
---
AWSTemplateFormatVersion: '2010-09-09'
Description: External Systems Stack - Interface VPC Endpoint
Resources:
  VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: com.amazonaws.ap-southeast-2.s3
      VpcId: vpc-12345678
      SubnetIds:
        - subnet-12345678
      SecurityGroupIds:
        - sg-12345678
      VpcEndpointType: Interface
