# 3. Datastore Profile CFN Template: RDS Instance
---
AWSTemplateFormatVersion: '2010-09-09'
Description: Datastore Stack - RDS Instance
Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: admin
      MasterUserPassword: YourSecurePassword123
      AllocatedStorage: 20
      StorageEncrypted: true
      PubliclyAccessible: false
